### ISSUE TITLE
Does it work with the newest version of TrackMate?

### ISSUE THREAD

**Issue by a-bio90** [tinevez/TrackMate-extras#8]
Hi, 
I extensively used the Extra for TrackMate to export detection as ROIs. Since I updated to TrackMate v7 it give errors (reported below) and it doesn't seem to work. I am far from being an expert in plugins management, so is there an easy way to solve this issue? Thank you

`java.util.concurrent.ExecutionException: java.lang.AbstractMethodError: Method fiji/plugin/trackmate/extra/spotanalyzer/SpotMultiChannelIntensityAnalyzerFactory.getAnalyzer(Lnet/imagej/ImgPlus;II)Lfiji/plugin/trackmate/features/spot/SpotAnalyzer; is abstract
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at fiji.plugin.trackmate.features.SpotFeatureCalculator.computeSpotFeaturesAgent(SpotFeatureCalculator.java:227)
	at fiji.plugin.trackmate.features.SpotFeatureCalculator.process(SpotFeatureCalculator.java:119)
	at fiji.plugin.trackmate.TrackMate.computeSpotFeatures(TrackMate.java:166)
	at fiji.plugin.trackmate.gui.wizard.descriptors.SpotFilterDescriptor$1.run(SpotFilterDescriptor.java:144)
	at fiji.plugin.trackmate.gui.wizard.WizardController$1.run(WizardController.java:192)
Caused by: java.lang.AbstractMethodError: Method fiji/plugin/trackmate/extra/spotanalyzer/SpotMultiChannelIntensityAnalyzerFactory.getAnalyzer(Lnet/imagej/ImgPlus;II)Lfiji/plugin/trackmate/features/spot/SpotAnalyzer; is abstract
	at fiji.plugin.trackmate.extra.spotanalyzer.SpotMultiChannelIntensityAnalyzerFactory.getAnalyzer(SpotMultiChannelIntensityAnalyzerFactory.java)
	at fiji.plugin.trackmate.features.SpotFeatureCalculator$1.call(SpotFeatureCalculator.java:204)
	at fiji.plugin.trackmate.features.SpotFeatureCalculator$1.call(SpotFeatureCalculator.java:190)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "TrackMate action thread" java.lang.AbstractMethodError: Method fiji/plugin/trackmate/extra/action/RoiExporter$Factory.create()Lfiji/plugin/trackmate/action/TrackMateAction; is abstract
	at fiji.plugin.trackmate.extra.action.RoiExporter$Factory.create(RoiExporter.java)
	at fiji.plugin.trackmate.gui.components.ActionChooserPanel$1$1.run(ActionChooserPanel.java:87)`

**Comment by tinevez** [comment]
Hello.

No need for this: the features in this extension have been ported to the v7. I am going to archive this repo and remove mentions of it.
